name = "ai-brain"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "lore_db"
database_id = "46b7be0f-7873-4189-879b-c56058f951ea"

[[vectorize]]
binding = "VECTORIZE"
index_name = "lore_index"
