
# This is a file for you to write an un-named query.
# Only one un-named query is allowed per file.
query {
  bloodlineLinks{
    id
    source {
      id
      name
      role
      status
      threatLevel
      imageUrl
      metadata
    }
    target {
      id
      name
      role
      status
      threatLevel
      imageUrl
      metadata
    }
    relationType
    notes
    isClassified
  }
}