type Entity @table {
  id: String!
  name: String!
  role: String
  status: String! @default(value: "ACTIVE")
  threatLevel: String! @default(value: "LOW")
  imageUrl: String
  metadata: String
  creatorId: String!
}

type BloodlineLink @table {
  id: String!
  # Aynı tabloya iki kez referans verdiğimiz için isim (name) belirttik
  source: Entity! @ref
  target: Entity! @ref
  relationType: String!
  notes: String
  isClassified: Boolean! @default(value: false)
  creatorId: String!
}